[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmds = [
  "go mod download",
  "go run github.com/steebchen/prisma-client-go prefetch"
]

[phases.build]
cmds = [
  "go run github.com/steebchen/prisma-client-go generate",
  "go build -o out fourleaves.studio/manga-scraper/cmd/rest-server/main.go"
]

[start]
cmd = "./out"