[variables]
CGO_ENABLED = "1"

[phases.setup]
nixPkgs = ["go", "gcc"]

[phases.install]
cmds = [
  "go mod download",
  "go run github.com/steebchen/prisma-client-go prefetch"
]

[phases.build]
cmds = [
  "printenv > .env",
  "go run github.com/steebchen/prisma-client-go generate",
  "CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -ldflags \"-extldflags \\\"-static\\\"\" -o out fourleaves.studio/manga-scraper/cmd/cron-worker"
]

[start]
cmd = "./out"