definitions:
  CreateProviderRequest:
    properties:
      host:
        example: asuratoon.com
        type: string
      is_active:
        example: true
        type: boolean
      list_path:
        example: /manga/list-mode/
        type: string
      name:
        example: Asura Scans
        type: string
      scheme:
        example: https://
        type: string
      slug:
        example: asura
        type: string
    required:
    - host
    - is_active
    - list_path
    - name
    - scheme
    - slug
    type: object
  CreateScrapeRequest:
    properties:
      chapter:
        example: reincarnator-chapter-1
        type: string
      provider:
        example: asura
        type: string
      series:
        example: reincarnator
        type: string
      type:
        enum:
        - SERIES_LIST
        - SERIES_DETAIL
        - CHAPTER_LIST
        - CHAPTER_DETAIL
        example: CHAPTER_DETAIL
        type: string
    required:
    - provider
    - type
    type: object
  ResponseV1:
    properties:
      data: {}
      detail: {}
      error:
        type: boolean
      message:
        type: string
    type: object
  UpdateProviderRequest:
    properties:
      host:
        example: asuratoon.com
        type: string
      is_active:
        example: true
        type: boolean
      list_path:
        example: /manga/list-mode/
        type: string
      name:
        example: Asura Scans
        type: string
      scheme:
        example: https://
        type: string
    required:
    - host
    - is_active
    - list_path
    - name
    - scheme
    type: object
info:
  contact:
    email: admin@fourleaves.studio
    name: API Support
    url: https://manga-scraper.hostinger.fourleaves.studio/support
  description: This is a Manga Scraper API server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://manga-scraper.hostinger.fourleaves.studio/terms
  title: Manga Scraper API
  version: "1.0"
paths:
  /api/v1/chapters/{provider_slug}/{series_slug}:
    get:
      description: Get paginated chapter list
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Series slug
        example: reincarnator
        in: path
        name: series_slug
        required: true
        type: string
      - default: asc
        description: Sort order
        in: query
        name: sort
        type: string
      - description: Page
        example: "10"
        in: query
        name: page
        required: true
        type: string
      - description: Size
        example: "100"
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get paginated chapter list
      tags:
      - chapters
  /api/v1/chapters/{provider_slug}/{series_slug}/_all:
    get:
      description: Get all chapter list
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Series slug
        example: reincarnator
        in: path
        name: series_slug
        required: true
        type: string
      - default: asc
        description: Sort order
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get all chapter list
      tags:
      - chapters
  /api/v1/chapters/{provider_slug}/{series_slug}/_list:
    get:
      description: Get chapter list with series
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Series slug
        example: reincarnator
        in: path
        name: series_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get chapter list with series
      tags:
      - chapters
  /api/v1/chapters/{provider_slug}/{series_slug}/{chapter_slug}:
    get:
      description: Get chapter by slug
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Series slug
        example: reincarnator
        in: path
        name: series_slug
        required: true
        type: string
      - description: Chapter slug
        example: reincarnator-chapter-0
        in: path
        name: chapter_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get chapter by slug
      tags:
      - chapters
  /api/v1/chapters/{provider_slug}/{series_slug}/{chapter_slug}/_bc:
    get:
      description: Get chapter breadcrumbs
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Series slug
        example: reincarnator
        in: path
        name: series_slug
        required: true
        type: string
      - description: Chapter slug
        example: reincarnator-chapter-0
        in: path
        name: chapter_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get chapter breadcrumbs
      tags:
      - chapters
  /api/v1/providers:
    get:
      description: Get provider list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get provider list
      tags:
      - providers
    post:
      consumes:
      - application/json
      description: Create provider
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/CreateProviderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/ResponseV1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseV1'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ResponseV1'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ResponseV1'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      security:
      - TokenAuth: []
      summary: Create provider
      tags:
      - providers
  /api/v1/providers/{provider_slug}:
    get:
      description: Get provider by slug
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get provider by slug
      tags:
      - providers
    put:
      consumes:
      - application/json
      description: Update provider
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UpdateProviderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseV1'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ResponseV1'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      security:
      - TokenAuth: []
      summary: Update provider
      tags:
      - providers
  /api/v1/providers/{provider_slug}/_bc:
    get:
      description: Get provider breadcrumbs
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get provider breadcrumbs
      tags:
      - providers
  /api/v1/scrapers:
    post:
      consumes:
      - application/json
      description: Create scrape request
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/CreateScrapeRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/ResponseV1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseV1'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ResponseV1'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      security:
      - TokenAuth: []
      summary: Create scrape request
      tags:
      - scrapers
  /api/v1/scrapers/{id}:
    get:
      description: Get scrape request by ID
      parameters:
      - description: Request ID
        example: 550e8400-e29b-41d4-a716-446655440000
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ResponseV1'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      security:
      - TokenAuth: []
      summary: Get scrape request by ID
      tags:
      - scrapers
  /api/v1/series:
    get:
      description: Get series search result
      parameters:
      - description: Query
        example: warrior high school
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get series search result
      tags:
      - series
  /api/v1/series/{provider_slug}:
    get:
      description: Get paginated series list
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Page
        example: "10"
        in: query
        name: page
        required: true
        type: string
      - description: Size
        example: "100"
        in: query
        name: size
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get paginated series list
      tags:
      - series
    put:
      description: Feed the open search engine
      parameters:
      - description: Provider Slug
        in: path
        name: provider_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/ResponseV1'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      security:
      - TokenAuth: []
      summary: Feed the open search engine
      tags:
      - series
  /api/v1/series/{provider_slug}/_all:
    get:
      description: Get all series list
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - default: asc
        description: Sort order
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get all series list
      tags:
      - series
  /api/v1/series/{provider_slug}/{series_slug}:
    get:
      description: Get series by slug
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Series slug
        example: reincarnator
        in: path
        name: series_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get series by slug
      tags:
      - series
  /api/v1/series/{provider_slug}/{series_slug}/_bc:
    get:
      description: Get series breadcrumbs
      parameters:
      - description: Provider slug
        example: asura
        in: path
        name: provider_slug
        required: true
        type: string
      - description: Series slug
        example: reincarnator
        in: path
        name: series_slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ResponseV1'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get series breadcrumbs
      tags:
      - series
  /health:
    get:
      description: Get health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ResponseV1'
      summary: Get health check
securityDefinitions:
  TokenAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
